### PR TITLE
fix(pages): tags should be a list

### PR DESCRIPTION
**Pull request by ybenitezf**
Post and study cases should be tagged for more than one tag.

See attached SS

In the list:
image

In the result pages
image

The page code:
image

### CODE REVIEW

**Comment by alcantara2575** [comment]
image

**Comment by alcantara2575** [comment]
image

**Comment by alcantara2575** [comment]
- [ ] Update category info for every study-case, @sorice

**Comment by enmalidia** [comment]
> image

Debe verse así en fila pero, encima como sugiere el diseño en naranja

**Pull request merged**
